export const FEATURED_SLUGS = new Set([
  "cristiano_ronaldo",
  "kylian_mbappé",
  "lionel_messi",
  "lebron_james",
  "novak_djokovic",
  "micah_parsons",
  "stephen_curry",
  "patrick_mahomes",
  "victor_wembanyama",
  "iga_swiatek",
  "christian_mccaffrey",
  "shai_gilgeous_alexander"
]);

export const ALL_PLAYERS = [
  {
    "slug": "jude_bellingham",
    "name": "Jude Bellingham",
    "short": "BELLINGHAM",
    "sport": "Soccer",
    "team": "Real Madrid",
    "nationality": "English",
    "position": "Midfielder",
    "bio": "Jude Victor William Bellingham is an English professional footballer who plays as a midfielder for La Liga club Real Madrid and the England national team. Known for his exceptional work rate, playmaking ability,",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg/330px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg",
    "brand_score": 75.3,
    "tier": "Elite Influencer",
    "ig": 41186012,
    "ig_eng": 6.1,
    "yt": 0,
    "yt_views": 0,
    "trend": 44,
    "trend_dir": "declining",
    "market_value": 140,
    "sub": {
      "social": 88.3,
      "eng": 100,
      "trend": 43.6,
      "spon": 39,
      "val": 77.8
    },
    "sponsors": [
      "Adidas",
      "BMW",
      "IWC",
      "Cadbury"
    ],
    "featured": false,
    "tt": 12300000,
    "tw": 5200000,
    "fb": 3100000,
    "deal_val": 25,
    "age": 22,
    "titles": "La Liga 2024 · UCL 2024 · Bundesliga 2023"
  },
  {
    "slug": "erling_haaland",
    "name": "Erling Haaland",
    "short": "HAALAND",
    "sport": "Soccer",
    "team": "Manchester City",
    "nationality": "Norwegian",
    "position": "Forward",
    "bio": "Erling Braut Haaland is a Norwegian professional footballer who plays as a striker for Premier League club Manchester City and the Norway national team. Considered one of the best players in the world, and the greatest",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Erling_Haaland_June_2025.jpg/330px-Erling_Haaland_June_2025.jpg",
    "brand_score": 70.2,
    "tier": "Major Star",
    "ig": 32500000,
    "ig_eng": 3.8,
    "yt": 0,
    "yt_views": 0,
    "trend": 47,
    "trend_dir": "rising",
    "market_value": 200,
    "sub": {
      "social": 88.1,
      "eng": 76,
      "trend": 46.9,
      "spon": 36,
      "val": 100
    },
    "sponsors": [
      "Nike",
      "Hyperice",
      "Breitling",
      "Nespresso"
    ],
    "featured": false,
    "tt": 18200000,
    "tw": 3100000,
    "fb": 8200000,
    "deal_val": 30,
    "age": 25,
    "titles": "UCL 2023 · Premier League 2023 · Bundesliga ×3"
  },
  {
    "slug": "vinícius_júnior",
    "name": "Vinícius Júnior",
    "short": "JÚNIOR",
    "sport": "Soccer",
    "team": "Real Madrid",
    "nationality": "Brazilian",
    "position": "Forward",
    "bio": "Vinícius José Paixão de Oliveira Júnior, commonly known as Vinícius Júnior or Vini Jr., is a Brazilian professional footballer who plays as a forward for La Liga club Real Madrid and the Brazil national team. Considered",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg/330px-2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg",
    "brand_score": 68.7,
    "tier": "Major Star",
    "ig": 54000000,
    "ig_eng": 5.2,
    "yt": 79120,
    "yt_views": 0.1,
    "trend": 36,
    "trend_dir": "rising",
    "market_value": 150,
    "sub": {
      "social": 90.4,
      "eng": 100,
      "trend": 35.6,
      "spon": 0,
      "val": 83.3
    },
    "sponsors": [
      "Nike",
      "Red Bull",
      "Spotify"
    ],
    "featured": false,
    "tt": 22500000,
    "tw": 8400000,
    "fb": 12400000,
    "deal_val": 22,
    "age": 25,
    "titles": "UCL 2022 & 2024 · La Liga ×2 · Copa del Rey"
  },
  {
    "slug": "carlos_alcaraz",
    "name": "Carlos Alcaraz",
    "short": "ALCARAZ",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Spanish",
    "position": "Singles",
    "bio": "Carlos Alcaraz Garfia is a Spanish professional tennis player. He has been ranked world No. 1 in men's singles by the Association of Tennis Professionals (ATP), and finished as the year-end No. 1 in 2022 and 2025.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Carlos_Alcaraz_2025_FO.jpg/330px-Carlos_Alcaraz_2025_FO.jpg",
    "brand_score": 68.6,
    "tier": "Major Star",
    "ig": 8633316,
    "ig_eng": 7.6,
    "yt": 1085,
    "yt_views": 0,
    "trend": 28,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 82.5,
      "eng": 100,
      "trend": 28.5,
      "spon": 80,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Babolat",
      "Rolex",
      "Louis Vuitton"
    ],
    "featured": false,
    "tt": 7400000,
    "tw": 2100000,
    "fb": 2100000,
    "deal_val": 25,
    "age": 23,
    "titles": "Wimbledon ×2 · Roland Garros 2024 · US Open 2022"
  },
  {
    "slug": "pedri",
    "name": "Pedri",
    "short": "PEDRI",
    "sport": "Soccer",
    "team": "Barcelona",
    "nationality": "Spanish",
    "position": "Midfielder",
    "bio": "Pedro González López, more commonly known as Pedri, is a Spanish professional footballer who plays as a midfielder for La Liga club Barcelona and the Spain national team. Considered as one of the best midfielders in the",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Pedri.jpg/330px-Pedri.jpg",
    "brand_score": 64.4,
    "tier": "Major Star",
    "ig": 22407406,
    "ig_eng": 4.2,
    "yt": 2,
    "yt_views": 0,
    "trend": 43,
    "trend_dir": "stable",
    "market_value": 150,
    "sub": {
      "social": 85.8,
      "eng": 84.5,
      "trend": 43,
      "spon": 0,
      "val": 83.3
    },
    "sponsors": [
      "Nike",
      "Gillette"
    ],
    "featured": false,
    "tt": 8200000,
    "tw": 3200000,
    "fb": 5200000,
    "deal_val": 5,
    "age": 23,
    "titles": "La Liga 2025 · Copa del Rey 2025 · Euro 2021 Silver"
  },
  {
    "slug": "charles_leclerc",
    "name": "Charles Leclerc",
    "short": "LECLERC",
    "sport": "Formula 1",
    "team": "Ferrari",
    "nationality": "Monégasque",
    "position": "Driver",
    "bio": "Charles Marc Hervé Perceval Leclerc is a Monégasque racing driver who competes in Formula One for Ferrari. Leclerc was runner-up in the Formula One World Drivers' Championship in 2022 with Ferrari, and has won eight",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3978_by_Stepro_%28cropped2%29.jpg/330px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3978_by_Stepro_%28cropped2%29.jpg",
    "brand_score": 64.3,
    "tier": "Major Star",
    "ig": 23737384,
    "ig_eng": 7.2,
    "yt": 1109065,
    "yt_views": 1.1,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 86.0,
      "eng": 100,
      "trend": 0,
      "spon": 80,
      "val": 0
    },
    "sponsors": [
      "Richard Mille",
      "Rolex",
      "Bvlgari",
      "Ray-Ban"
    ],
    "featured": false,
    "tt": 5100000,
    "tw": 6100000,
    "fb": 4100000,
    "deal_val": 15,
    "age": 28,
    "titles": "Monaco GP 2024 · 25 Pole Positions · Ferrari Ace"
  },
  {
    "slug": "daniil_medvedev",
    "name": "Daniil Medvedev",
    "short": "MEDVEDEV",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Russian",
    "position": "Singles",
    "bio": "Daniil Sergeyevich Medvedev is a Russian professional tennis player. He has been ranked as the world No. 1 in men's singles by the Association of Tennis Professionals (ATP). Medvedev has won 23 ATP Tour-level singles",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Danill_Medvedev_Miami_2019_%28cropped%29.jpg/330px-Danill_Medvedev_Miami_2019_%28cropped%29.jpg",
    "brand_score": 63.2,
    "tier": "Major Star",
    "ig": 2900000,
    "ig_eng": 5.8,
    "yt": 46,
    "yt_views": 0,
    "trend": 21,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 77.1,
      "eng": 100,
      "trend": 20.9,
      "spon": 64,
      "val": 0
    },
    "sponsors": [
      "Lacoste",
      "Tecnifibre",
      "BMW",
      "Bovet Fleurier"
    ],
    "featured": false,
    "tt": 1600000,
    "tw": 1480000,
    "fb": 1050000,
    "deal_val": 12,
    "age": 30,
    "titles": "US Open 2021 · ATP Finals ×2 · ATP World No.1"
  },
  {
    "slug": "jayson_tatum",
    "name": "Jayson Tatum",
    "short": "TATUM",
    "sport": "Basketball",
    "team": "Boston Celtics",
    "nationality": "American",
    "position": "Forward",
    "bio": "Jayson Christopher Tatum Sr. is an American professional basketball player for the Boston Celtics of the National Basketball Association (NBA). He was a McDonald's All-American in high school in Missouri and played",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg/330px-Celtics_at_Wizards_2024-12-044_%28cropped_2%29.jpg",
    "brand_score": 62.8,
    "tier": "Major Star",
    "ig": 10200000,
    "ig_eng": 3.6,
    "yt": 85437,
    "yt_views": 0.1,
    "trend": 24,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 82.4,
      "eng": 83.2,
      "trend": 23.6,
      "spon": 80,
      "val": 0
    },
    "sponsors": [
      "Jordan Brand",
      "Subway",
      "State Farm"
    ],
    "featured": false,
    "tt": 3100000,
    "tw": 4200000,
    "fb": 2200000,
    "deal_val": 12,
    "age": 28,
    "titles": "NBA Champion 2024 · All-Star ×5 · Olympic Gold 2024"
  },
  {
    "slug": "luka_dončić",
    "name": "Luka Dončić",
    "short": "DONČIĆ",
    "sport": "Basketball",
    "team": "Dallas Mavericks",
    "nationality": "Slovenian",
    "position": "Guard",
    "bio": "Luka Dončić is a Slovenian professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). Since his rookie season, he has been selected to six NBA All-Star games and six All-NBA",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Luka_Doncic_%2851914951721%29_%28cropped1%29.jpg/330px-Luka_Doncic_%2851914951721%29_%28cropped1%29.jpg",
    "brand_score": 60,
    "tier": "Major Star",
    "ig": 14800000,
    "ig_eng": 4.9,
    "yt": 29266,
    "yt_views": 0,
    "trend": 44,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 84.9,
      "eng": 98.8,
      "trend": 43.5,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Jordan Brand",
      "Panini",
      "Sportradar"
    ],
    "featured": false,
    "tt": 9100000,
    "tw": 5100000,
    "fb": 4200000,
    "deal_val": 15,
    "age": 27,
    "titles": "NBA Champion 2024 · EuroLeague 2018 · MVP ×4"
  },
  {
    "slug": "rodri",
    "name": "Rodri",
    "short": "RODRI",
    "sport": "Soccer",
    "team": "Manchester City",
    "nationality": "Spanish",
    "position": "Midfielder",
    "bio": "Rodrigo Hernández Cascante, known as Rodri or Rodrigo, is a Spanish professional footballer who plays as a defensive midfielder for Premier League club Manchester City and captains the Spain national team. Known for his",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/RODRI_-_SWE_vs_ESP_-_UEFA_EURO_2020_QUALIFIERS_-_2019.10.15_%28cropped%29.jpg/500px-RODRI_-_SWE_vs_ESP_-_UEFA_EURO_2020_QUALIFIERS_-_2019.10.15_%28cropped%29.jpg",
    "brand_score": 57.6,
    "tier": "Major Star",
    "ig": 8200000,
    "ig_eng": 3.1,
    "yt": 9065,
    "yt_views": 0,
    "trend": 50,
    "trend_dir": "stable",
    "market_value": 65,
    "sub": {
      "social": 81.2,
      "eng": 77.2,
      "trend": 49.9,
      "spon": 0,
      "val": 36.1
    },
    "sponsors": [
      "Adidas",
      "Santander"
    ],
    "featured": false,
    "tt": 3400000,
    "tw": 2100000,
    "fb": 1500000,
    "deal_val": 4,
    "age": 29,
    "titles": "Ballon d'Or 2024 · UCL 2023 · Euro 2024"
  },
  {
    "slug": "kylian_mbappé",
    "name": "Kylian Mbappé",
    "short": "MBAPPE",
    "sport": "Soccer",
    "team": "Real Madrid",
    "nationality": "French",
    "position": "Forward",
    "bio": "Kylian Mbappé Lottin is a French professional footballer who plays as a forward for La Liga club Real Madrid and captains the France national team. Widely regarded as one of the best players in the world, he is known",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg/330px-Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg",
    "brand_score": 57.3,
    "tier": "Major Star",
    "ig": 130320964,
    "ig_eng": 0.9,
    "yt": 1190745,
    "yt_views": 1.2,
    "trend": 38,
    "trend_dir": "rising",
    "market_value": 200,
    "sub": {
      "social": 94.4,
      "eng": 51.3,
      "trend": 37.5,
      "spon": 0,
      "val": 100
    },
    "sponsors": [
      "Nike",
      "Hublot",
      "EA Sports",
      "Dior",
      "Oakley"
    ],
    "featured": true,
    "tt": 28000000,
    "tw": 15200000,
    "fb": 50000000,
    "deal_val": 55,
    "age": 27,
    "titles": "World Cup 2018 · UCL 2024 · Ligue 1 ×7"
  },
  {
    "slug": "virat_kohli",
    "name": "Virat Kohli",
    "short": "KOHLI",
    "sport": "Cricket",
    "team": "India",
    "nationality": "Indian",
    "position": "Batsman",
    "bio": "Virat Kohli is an Indian international cricketer and the former all-format captain of the Indian national cricket team. He is a right-handed batter and occasional right-arm medium pace bowler. Considered one of the",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Virat_Kohli_in_PMO_New_Delhi.jpg/330px-Virat_Kohli_in_PMO_New_Delhi.jpg",
    "brand_score": 57.1,
    "tier": "Major Star",
    "ig": 273474390,
    "ig_eng": 3,
    "yt": 0,
    "yt_views": 0,
    "trend": 27,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 97.4,
      "eng": 59.4,
      "trend": 27.4,
      "spon": 59,
      "val": 0
    },
    "sponsors": [
      "Puma",
      "MRF",
      "Audi",
      "Boost",
      "American Tourister"
    ],
    "featured": false,
    "tt": 15300000,
    "tw": 58200000,
    "fb": 50000000,
    "deal_val": 35,
    "age": 37,
    "titles": "T20 WC 2024 · ICC WC 2011 · 100 Int'l Centuries"
  },
  {
    "slug": "kevin_durant",
    "name": "Kevin Durant",
    "short": "DURANT",
    "sport": "Basketball",
    "team": "Phoenix Suns",
    "nationality": "American",
    "position": "Forward",
    "bio": "Kevin Wayne Durant, also known by his initials KD, is an American professional basketball player for the Houston Rockets of the National Basketball Association (NBA). Nicknamed \"the Slim Reaper\", he is widely regarded",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg/500px-Kevin_Durant%2C_Paris_2024_%28cropped%29.jpg",
    "brand_score": 56,
    "tier": "Major Star",
    "ig": 13366705,
    "ig_eng": 6.4,
    "yt": 901,
    "yt_views": 0,
    "trend": 23,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 86.1,
      "eng": 100,
      "trend": 22.7,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Gatorade",
      "Alaska Airlines",
      "Coinbase"
    ],
    "featured": false,
    "tt": 6200000,
    "tw": 16400000,
    "fb": 10200000,
    "deal_val": 25,
    "age": 37,
    "titles": "NBA Champion ×2 · Finals MVP ×2 · Olympic Gold ×3"
  },
  {
    "slug": "jannik_sinner",
    "name": "Jannik Sinner",
    "short": "SINNER",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Italian",
    "position": "Singles",
    "bio": "Jannik Sinner is an Italian professional tennis player. He is currently ranked world No.1 by Association of Tennis Professionals (ATP), and was the year-end No. 1 in 2024. Sinner has won 29 ATP Tour–level singles",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Jannik_Sinner_2025_US_Open.jpg/330px-Jannik_Sinner_2025_US_Open.jpg",
    "brand_score": 55.9,
    "tier": "Major Star",
    "ig": 5455488,
    "ig_eng": 10.8,
    "yt": 275511,
    "yt_views": 0.3,
    "trend": 28,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 80.4,
      "eng": 100,
      "trend": 27.7,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Babolat",
      "Rolex",
      "Swarovski"
    ],
    "featured": false,
    "tt": 4600000,
    "tw": 1560000,
    "fb": 1500000,
    "deal_val": 15,
    "age": 24,
    "titles": "Australian Open ×2 · US Open 2024 · ATP World No.1"
  },
  {
    "slug": "taylor_fritz",
    "name": "Taylor Fritz",
    "short": "FRITZ",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "American",
    "position": "Singles",
    "bio": "Taylor Harry Fritz is an American professional tennis player. He has been ranked by the Association of Tennis Professionals (ATP) as high as world No. 4 in singles, which he achieved on November 18, 2024, and No. 104 in",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Taylor_Fritz_-_Delray_Beach_Open_Final_Round_%28cropped%29.jpg/330px-Taylor_Fritz_-_Delray_Beach_Open_Final_Round_%28cropped%29.jpg",
    "brand_score": 55.9,
    "tier": "Major Star",
    "ig": 820000,
    "ig_eng": 4.2,
    "yt": 362,
    "yt_views": 0,
    "trend": 13,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 71.8,
      "eng": 90.4,
      "trend": 13,
      "spon": 56,
      "val": 0
    },
    "sponsors": [
      "Hugo Boss",
      "Head",
      "Rolex"
    ],
    "featured": false,
    "tt": 820000,
    "tw": 480000,
    "fb": 310000,
    "deal_val": 6,
    "age": 28,
    "titles": "Indian Wells 2022 · ATP Top 5 · Davis Cup"
  },
  {
    "slug": "alexander_zverev",
    "name": "Alexander Zverev",
    "short": "ZVEREV",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "German",
    "position": "Singles",
    "bio": "Alexander \"Sascha\" Zverev is a German professional tennis player and the current world No. 3. He has been ranked as high as world No. 2 in men's singles by the Association of Tennis Professionals (ATP), achieved in June",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Alexander_Zverev.jpg/500px-Alexander_Zverev.jpg",
    "brand_score": 54.4,
    "tier": "Rising Brand",
    "ig": 3100000,
    "ig_eng": 4.7,
    "yt": 5,
    "yt_views": 0,
    "trend": 29,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 77.6,
      "eng": 96.4,
      "trend": 29.4,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Adidas",
      "Head",
      "Rolex",
      "Porsche"
    ],
    "featured": false,
    "tt": 2100000,
    "tw": 1520000,
    "fb": 1100000,
    "deal_val": 15,
    "age": 29,
    "titles": "Roland Garros 2025 · Olympic Gold 2020 · ATP Finals ×3"
  },
  {
    "slug": "nikola_jokić",
    "name": "Nikola Jokić",
    "short": "JOKIĆ",
    "sport": "Basketball",
    "team": "Denver Nuggets",
    "nationality": "Serbian",
    "position": "Center",
    "bio": "Nikola Jokić is a Serbian professional basketball player who is a center for the Denver Nuggets of the National Basketball Association (NBA). Nicknamed \"Joker\", he is widely regarded as one of the greatest players and",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Nikola_Jokic_free_throw_%28cropped%29.jpg/330px-Nikola_Jokic_free_throw_%28cropped%29.jpg",
    "brand_score": 54.1,
    "tier": "Rising Brand",
    "ig": 2100000,
    "ig_eng": 4.5,
    "yt": 2670,
    "yt_views": 0,
    "trend": 34,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 75.2,
      "eng": 94,
      "trend": 34.5,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Peak",
      "USAA"
    ],
    "featured": false,
    "tt": 1250000,
    "tw": 820000,
    "fb": 510000,
    "deal_val": 5,
    "age": 31,
    "titles": "NBA Champion ×2 · MVP ×3 · Finals MVP ×2"
  },
  {
    "slug": "robert_lewandowski",
    "name": "Robert Lewandowski",
    "short": "LEWANDOWSKI",
    "sport": "Soccer",
    "team": "Barcelona",
    "nationality": "Polish",
    "position": "Forward",
    "bio": "Robert Lewandowski is a Polish professional footballer who plays as a striker for La Liga club Barcelona and captains the Poland national team. Widely regarded as one of the greatest strikers of all time, he is one of",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg/330px-2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg",
    "brand_score": 54.1,
    "tier": "Rising Brand",
    "ig": 38848581,
    "ig_eng": 4.1,
    "yt": 12497,
    "yt_views": 0,
    "trend": 21,
    "trend_dir": "rising",
    "market_value": 8,
    "sub": {
      "social": 88.3,
      "eng": 88.9,
      "trend": 20.7,
      "spon": 0,
      "val": 4.4
    },
    "sponsors": [
      "Nike",
      "Huawei",
      "EFG",
      "Sorare"
    ],
    "featured": false,
    "tt": 7100000,
    "tw": 4300000,
    "fb": 15200000,
    "deal_val": 10,
    "age": 37,
    "titles": "Bundesliga ×8 · UCL 2020 · La Liga ×2"
  },
  {
    "slug": "lewis_hamilton",
    "name": "Lewis Hamilton",
    "short": "HAMILTON",
    "sport": "Formula 1",
    "team": "Ferrari",
    "nationality": "British",
    "position": "Driver",
    "bio": "Sir Lewis Carl Davidson Hamilton is a British racing driver who competes in Formula One for Ferrari. Hamilton has won a joint-record seven Formula One World Drivers' Championship titles—tied with Michael Schumacher—and",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg/330px-Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg",
    "brand_score": 53.5,
    "tier": "Rising Brand",
    "ig": 42630446,
    "ig_eng": 2.6,
    "yt": 701595,
    "yt_views": 0.7,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 88.9,
      "eng": 69,
      "trend": 0,
      "spon": 63,
      "val": 0
    },
    "sponsors": [
      "Ferrari",
      "Tommy Hilfiger",
      "Monster Energy",
      "IWC",
      "Puma"
    ],
    "featured": false,
    "tt": 10400000,
    "tw": 7900000,
    "fb": 10200000,
    "deal_val": 70,
    "age": 41,
    "titles": "F1 World Champion ×7 · 103 Race Wins · All-Time Record"
  },
  {
    "slug": "aryna_sabalenka",
    "name": "Aryna Sabalenka",
    "short": "SABALENKA",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Belarusian",
    "position": "Singles",
    "bio": "Aryna Siarhiejeŭna Sabalenka is a Belarusian professional tennis player. She is the current world No. 1 in women's singles by the WTA and is a former No. 1 in doubles. Sabalenka has won 24 WTA Tour-level singles titles,",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Aryna_Sabalenka_%282024_DC_Open%29_06.jpg/330px-Aryna_Sabalenka_%282024_DC_Open%29_06.jpg",
    "brand_score": 53.1,
    "tier": "Rising Brand",
    "ig": 5165782,
    "ig_eng": 4.1,
    "yt": 129715,
    "yt_views": 0.1,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 79.2,
      "eng": 89.5,
      "trend": 0,
      "spon": 40,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Wilson",
      "Emirates"
    ],
    "featured": false,
    "tt": 2600000,
    "tw": 1050000,
    "fb": 1500000,
    "deal_val": 8,
    "age": 28,
    "titles": "Australian Open ×3 · US Open 2023 · WTA World No.1"
  },
  {
    "slug": "jasprit_bumrah",
    "name": "Jasprit Bumrah",
    "short": "BUMRAH",
    "sport": "Cricket",
    "team": "India",
    "nationality": "Indian",
    "position": "Bowler",
    "bio": "Jasprit Jasbirsingh Bumrah is an Indian International cricketer who plays for the Indian national cricket team in all formats of this game and has captained India in Tests and T20Is. He is widely regarded as the",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Jasprit_Bumrah_in_PMO_New_Delhi.jpg/330px-Jasprit_Bumrah_in_PMO_New_Delhi.jpg",
    "brand_score": 51.9,
    "tier": "Rising Brand",
    "ig": 18400000,
    "ig_eng": 5.9,
    "yt": 464987,
    "yt_views": 0.5,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 85.7,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "MRF",
      "Bharat Petroleum",
      "Gulf Oil"
    ],
    "featured": false,
    "tt": 4100000,
    "tw": 10300000,
    "fb": 7100000,
    "deal_val": 6,
    "age": 32,
    "titles": "T20 WC 2024 · ICC No.1 Bowler · 350+ Int'l Wickets"
  },
  {
    "slug": "max_verstappen",
    "name": "Max Verstappen",
    "short": "VERSTAPPEN",
    "sport": "Formula 1",
    "team": "Red Bull Racing",
    "nationality": "Dutch",
    "position": "Driver",
    "bio": "Max Emilian Verstappen is a Dutch and Belgian racing driver who competes under the Dutch flag in Formula One for Red Bull Racing. Verstappen has won four Formula One World Drivers' Championship titles, which he won",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg/330px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg",
    "brand_score": 51.6,
    "tier": "Rising Brand",
    "ig": 18582952,
    "ig_eng": 3,
    "yt": 701556,
    "yt_views": 0.7,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 85.8,
      "eng": 74,
      "trend": 0,
      "spon": 45,
      "val": 0
    },
    "sponsors": [
      "Red Bull",
      "Rauch",
      "Jumbo",
      "Ziggo"
    ],
    "featured": false,
    "tt": 9200000,
    "tw": 6200000,
    "fb": 5100000,
    "deal_val": 40,
    "age": 28,
    "titles": "F1 World Champion ×4 · 63 Race Wins · All-Time Record"
  },
  {
    "slug": "babar_azam",
    "name": "Babar Azam",
    "short": "AZAM",
    "sport": "Cricket",
    "team": "Pakistan",
    "nationality": "Pakistani",
    "position": "Batsman",
    "bio": "Mohammad Babar Azam is a Pakistani international cricketer and a former captain of the Pakistan national team in all three formats of the game. A right-handed top-order batter, he captains Peshawar Zalmi in the Pakistan",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Babar_azam_2023.jpg/330px-Babar_azam_2023.jpg",
    "brand_score": 51.5,
    "tier": "Rising Brand",
    "ig": 13500000,
    "ig_eng": 6.1,
    "yt": 396,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 84.9,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Kia",
      "Pepsi",
      "Servis"
    ],
    "featured": false,
    "tt": 5200000,
    "tw": 8100000,
    "fb": 8200000,
    "deal_val": 6,
    "age": 31,
    "titles": "ICC No.1 Ranked Batter · PSL Captain"
  },
  {
    "slug": "andrey_rublev",
    "name": "Andrey Rublev",
    "short": "RUBLEV",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Russian",
    "position": "Singles",
    "bio": "Andrey Andreyevich Rublev is a Russian professional tennis player. He has been ranked by the ATP as high as world No. 5 in singles, which he achieved on 13 September 2021, and No. 44 in doubles, attained on 6 November",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Andrey_Rublev_%282023_US_Open%29_02_%28cropped%29.jpg/500px-Andrey_Rublev_%282023_US_Open%29_02_%28cropped%29.jpg",
    "brand_score": 51.1,
    "tier": "Rising Brand",
    "ig": 622448,
    "ig_eng": 5.1,
    "yt": 243,
    "yt_views": 0,
    "trend": 18,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 71.5,
      "eng": 100,
      "trend": 18,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Lotto Sport",
      "Wilson",
      "Rolex"
    ],
    "featured": false,
    "tt": 920000,
    "tw": 510000,
    "fb": 320000,
    "deal_val": 4,
    "age": 28,
    "titles": "ATP Finals 2024 · Davis Cup 2021 · ATP Top 5"
  },
  {
    "slug": "george_russell",
    "name": "George Russell",
    "short": "RUSSELL",
    "sport": "Formula 1",
    "team": "Mercedes",
    "nationality": "British",
    "position": "Driver",
    "bio": "George William Russell is a British racing driver who competes in Formula One for Mercedes. Russell has won six Formula One Grands Prix across eight seasons.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/KingsLeonSilverstne040724_%2828_of_112%29_%2853838006028%29_%28cropped%29.jpg/330px-KingsLeonSilverstne040724_%2828_of_112%29_%2853838006028%29_%28cropped%29.jpg",
    "brand_score": 50.9,
    "tier": "Rising Brand",
    "ig": 8795415,
    "ig_eng": 5.8,
    "yt": 19739,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 81.9,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Mercedes",
      "Tommy Hilfiger",
      "IWC"
    ],
    "featured": false,
    "tt": 3200000,
    "tw": 3900000,
    "fb": 2100000,
    "deal_val": 8,
    "age": 28,
    "titles": "Brazilian GP 2022 · 2 Race Wins · Mercedes Driver"
  },
  {
    "slug": "lando_norris",
    "name": "Lando Norris",
    "short": "NORRIS",
    "sport": "Formula 1",
    "team": "McLaren",
    "nationality": "British",
    "position": "Driver",
    "bio": "Lando Norris is a British racing driver who competes in Formula One for McLaren. Norris won the Formula One World Drivers' Championship in 2025 with McLaren, and has won 11 Grands Prix across eight seasons.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3968_by_Stepro_%28cropped2%29.jpg/330px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3968_by_Stepro_%28cropped2%29.jpg",
    "brand_score": 50.9,
    "tier": "Rising Brand",
    "ig": 8900000,
    "ig_eng": 6.4,
    "yt": 0,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 83.6,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "McLaren",
      "GoPro",
      "OKX",
      "Huski Chocolate"
    ],
    "featured": false,
    "tt": 9400000,
    "tw": 5200000,
    "fb": 3200000,
    "deal_val": 15,
    "age": 26,
    "titles": "F1 WC Runner-Up 2024 · 6 Race Wins · McLaren Lead"
  },
  {
    "slug": "oscar_piastri",
    "name": "Oscar Piastri",
    "short": "PIASTRI",
    "sport": "Formula 1",
    "team": "McLaren",
    "nationality": "Australian",
    "position": "Driver",
    "bio": "Oscar Jack Piastri is an Australian racing driver who competes in Formula One for McLaren. Piastri has won nine Formula One Grands Prix across four seasons.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/2026_Chinese_GP_-_Oscar_Piastri_%28cropped%29_%28cropped%29.jpg/330px-2026_Chinese_GP_-_Oscar_Piastri_%28cropped%29_%28cropped%29.jpg",
    "brand_score": 50.5,
    "tier": "Rising Brand",
    "ig": 6431098,
    "ig_eng": 8.1,
    "yt": 25261,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 80.3,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "McLaren",
      "Hilton",
      "OKX"
    ],
    "featured": false,
    "tt": 3050000,
    "tw": 2100000,
    "fb": 1520000,
    "deal_val": 6,
    "age": 25,
    "titles": "Australian GP 2025 · F2 Champion 2021 · McLaren Star"
  },
  {
    "slug": "holger_rune",
    "name": "Holger Rune",
    "short": "RUNE",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Danish",
    "position": "Singles",
    "bio": "Holger Vitus Nødskov Rune is a Danish professional tennis player. He has been ranked as high as world No. 4 in singles by the ATP, making him the highest-ranked Danish man in the history of tennis. Rune has won five ATP",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rune_RG22_%284%29_%2852144534990%29.jpg/500px-Rune_RG22_%284%29_%2852144534990%29.jpg",
    "brand_score": 50.2,
    "tier": "Rising Brand",
    "ig": 1046798,
    "ig_eng": 4.5,
    "yt": 2114,
    "yt_views": 0,
    "trend": 19,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 73.7,
      "eng": 94.4,
      "trend": 18.6,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Puma",
      "Babolat",
      "Rolex"
    ],
    "featured": false,
    "tt": 1550000,
    "tw": 480000,
    "fb": 520000,
    "deal_val": 5,
    "age": 23,
    "titles": "Paris Masters 2022 · ATP Top 10"
  },
  {
    "slug": "neymar_jr",
    "name": "Neymar Jr.",
    "short": "JR.",
    "sport": "Soccer",
    "team": "Al Hilal",
    "nationality": "Brazilian",
    "position": "Forward",
    "bio": "Neymar da Silva Santos Júnior, simply known as Neymar Júnior or mononymously as Neymar, is a Brazilian professional footballer who plays as an attacking midfielder or a forward for Campeonato Brasileiro Série A club",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg/330px-Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg",
    "brand_score": 50,
    "tier": "Rising Brand",
    "ig": 233310009,
    "ig_eng": 1.4,
    "yt": 2912480,
    "yt_views": 2.9,
    "trend": 39,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 97.5,
      "eng": 57,
      "trend": 39.3,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Puma",
      "Red Bull",
      "Mastercard"
    ],
    "featured": false,
    "tt": 25400000,
    "tw": 60500000,
    "fb": 100000000,
    "deal_val": 18,
    "age": 34,
    "titles": "Copa América 2019 · UCL 2015 · La Liga ×2"
  },
  {
    "slug": "shakib_al_hasan",
    "name": "Shakib Al Hasan",
    "short": "HASAN",
    "sport": "Cricket",
    "team": "Bangladesh",
    "nationality": "Bangladeshi",
    "position": "All-rounder",
    "bio": "Shakib Al Hasan is a Bangladeshi international cricketer and captain who played Test, ODI and T20I cricket for the Bangladeshi cricket team. He was a former member of Parliament for Magura-1. He is known for his",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Shakib_Al_Hasan_2023_03.jpg/500px-Shakib_Al_Hasan_2023_03.jpg",
    "brand_score": 50,
    "tier": "Rising Brand",
    "ig": 4200000,
    "ig_eng": 5.3,
    "yt": 216663,
    "yt_views": 0.2,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 82.1,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Walton",
      "Kookaburra",
      "Robi"
    ],
    "featured": false,
    "tt": 2100000,
    "tw": 5400000,
    "fb": 10200000,
    "deal_val": 3,
    "age": 39,
    "titles": "Asia Cup ×2 · ICC No.1 All-Rounder · 700+ Int'l Wickets"
  },
  {
    "slug": "steve_smith",
    "name": "Steve Smith",
    "short": "SMITH",
    "sport": "Cricket",
    "team": "Australia",
    "nationality": "Australian",
    "position": "Batsman",
    "bio": "Steven Peter Devereux Smith is an Australian international cricketer, former captain of the Australian national team in all three formats of the game and since 2021, the vice-captain of the Australian Test team. He is",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/STEVE_SMITH_%2811705303043%29.jpg/500px-STEVE_SMITH_%2811705303043%29.jpg",
    "brand_score": 49.9,
    "tier": "Rising Brand",
    "ig": 3981410,
    "ig_eng": 5.5,
    "yt": 53239,
    "yt_views": 0.1,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 76.6,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "ASICS",
      "Kookaburra",
      "Nitro"
    ],
    "featured": false,
    "tt": 510000,
    "tw": 820000,
    "fb": 510000,
    "deal_val": 4,
    "age": 36,
    "titles": "ICC WC 2015 · Ashes 2019 Hero · Test Avg 59+"
  },
  {
    "slug": "pat_cummins",
    "name": "Pat Cummins",
    "short": "CUMMINS",
    "sport": "Cricket",
    "team": "Australia",
    "nationality": "Australian",
    "position": "Bowler",
    "bio": "Patrick James Cummins is an Australian international cricketer who plays for the Australian men's cricket team in all three formats, captaining the team in both Test and One Day International cricket. A right-armed pace",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Pat_Cummins_fielding_Ashes_2021_%28cropped%29.jpg/500px-Pat_Cummins_fielding_Ashes_2021_%28cropped%29.jpg",
    "brand_score": 49.6,
    "tier": "Rising Brand",
    "ig": 3281222,
    "ig_eng": 10.1,
    "yt": 6889,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 77.5,
      "eng": 100,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "ASICS",
      "Kookaburra",
      "Puma"
    ],
    "featured": false,
    "tt": 1050000,
    "tw": 2200000,
    "fb": 1050000,
    "deal_val": 4,
    "age": 33,
    "titles": "ICC WC 2023 · WTC 2023 Captain · Ashes 2023"
  },
  {
    "slug": "casper_ruud",
    "name": "Casper Ruud",
    "short": "RUUD",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Norwegian",
    "position": "Singles",
    "bio": "Casper Ruud is a Norwegian professional tennis player. He has been ranked as high as world No. 2 in men's singles by the ATP, achieved in September 2022, making him the highest-ranked Norwegian in history. Ruud has won",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Ruud_RG22_%2858%29_%2852144535415%29.jpg/330px-Ruud_RG22_%2858%29_%2852144535415%29.jpg",
    "brand_score": 47.5,
    "tier": "Rising Brand",
    "ig": 787645,
    "ig_eng": 4.1,
    "yt": 115422,
    "yt_views": 0.1,
    "trend": 14,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 71.7,
      "eng": 89.5,
      "trend": 14.1,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Babolat",
      "Rolex"
    ],
    "featured": false,
    "tt": 820000,
    "tw": 320000,
    "fb": 310000,
    "deal_val": 5,
    "age": 27,
    "titles": "Roland Garros Finalist ×2 · ATP Top 5"
  },
  {
    "slug": "kevin_de_bruyne",
    "name": "Kevin De Bruyne",
    "short": "BRUYNE",
    "sport": "Soccer",
    "team": "Manchester City",
    "nationality": "Belgian",
    "position": "Midfielder",
    "bio": "Kevin De Bruyne is a Belgian professional footballer who plays as a midfielder for Serie A club Napoli and the Belgium national team. Widely regarded as one of the best players of his generation and one of the best",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/500px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg",
    "brand_score": 47.5,
    "tier": "Rising Brand",
    "ig": 26265636,
    "ig_eng": 1.8,
    "yt": 433,
    "yt_views": 0,
    "trend": 31,
    "trend_dir": "declining",
    "market_value": 10,
    "sub": {
      "social": 86.3,
      "eng": 61.4,
      "trend": 30.7,
      "spon": 0,
      "val": 5.6
    },
    "sponsors": [
      "Nike",
      "Lotus Cars",
      "Eleven Sports"
    ],
    "featured": false,
    "tt": 4100000,
    "tw": 4900000,
    "fb": 8100000,
    "deal_val": 8,
    "age": 34,
    "titles": "Premier League ×6 · UCL 2023 · FA Cup 2023"
  },
  {
    "slug": "kawhi_leonard",
    "name": "Kawhi Leonard",
    "short": "LEONARD",
    "sport": "Basketball",
    "team": "LA Clippers",
    "nationality": "American",
    "position": "Forward",
    "bio": "Kawhi Anthony Leonard is an American professional basketball player for the Los Angeles Clippers of the National Basketball Association (NBA). A two-time NBA champion and Finals MVP, he is a seven-time All-Star and",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Kawhi_Leonard_%287440607%29_%28cropped%29.jpg/500px-Kawhi_Leonard_%287440607%29_%28cropped%29.jpg",
    "brand_score": 45.8,
    "tier": "Rising Brand",
    "ig": 3800000,
    "ig_eng": 2.1,
    "yt": 393,
    "yt_views": 0,
    "trend": 32,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 77.8,
      "eng": 65.2,
      "trend": 32.2,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "New Balance",
      "Panini",
      "Honey"
    ],
    "featured": false,
    "tt": 950000,
    "tw": 2200000,
    "fb": 1100000,
    "deal_val": 8,
    "age": 34,
    "titles": "NBA Champion ×2 · Finals MVP ×2 · DPOY ×2"
  },
  {
    "slug": "lebron_james",
    "name": "LeBron James",
    "short": "LEBRON",
    "sport": "Basketball",
    "team": "Los Angeles Lakers",
    "nationality": "American",
    "position": "Forward",
    "bio": "LeBron Raymone James is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). Nicknamed \"King James\", he is the NBA's all-time leading scorer and has won",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/330px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg",
    "brand_score": 45.8,
    "tier": "Rising Brand",
    "ig": 154017883,
    "ig_eng": 0.1,
    "yt": 0,
    "yt_views": 0,
    "trend": 50,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 95.1,
      "eng": 3,
      "trend": 49.7,
      "spon": 69,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Beats",
      "Blaze Pizza",
      "Walmart",
      "AT&T",
      "PepsiCo"
    ],
    "featured": true,
    "tt": 24100000,
    "tw": 52400000,
    "fb": 22000000,
    "deal_val": 65,
    "age": 41,
    "titles": "NBA Champion ×4 · MVP ×4 · Olympic Gold ×3"
  },
  {
    "slug": "mohamed_salah",
    "name": "Mohamed Salah",
    "short": "SALAH",
    "sport": "Soccer",
    "team": "Liverpool",
    "nationality": "Egyptian",
    "position": "Forward",
    "bio": "Mohamed Salah Hamed Mahrous Ghaly is an Egyptian professional footballer who plays as a right winger or right midfielder for Premier League club Liverpool and captains the Egypt national team. He is widely regarded as",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mohamed_Salah_2018.jpg/330px-Mohamed_Salah_2018.jpg",
    "brand_score": 44.8,
    "tier": "Rising Brand",
    "ig": 65333456,
    "ig_eng": 1.4,
    "yt": 0,
    "yt_views": 0,
    "trend": 20,
    "trend_dir": "rising",
    "market_value": 30,
    "sub": {
      "social": 91.9,
      "eng": 28.6,
      "trend": 20.1,
      "spon": 47,
      "val": 16.7
    },
    "sponsors": [
      "Adidas",
      "Vodafone",
      "HSBC",
      "Pepsi"
    ],
    "featured": false,
    "tt": 11800000,
    "tw": 12100000,
    "fb": 55000000,
    "deal_val": 18,
    "age": 33,
    "titles": "UCL 2019 · Premier League 2020 · FA Cup 2022"
  },
  {
    "slug": "ben_stokes",
    "name": "Ben Stokes",
    "short": "STOKES",
    "sport": "Cricket",
    "team": "England",
    "nationality": "English",
    "position": "All-rounder",
    "bio": "Benjamin Andrew Stokes is an English international cricketer who is the captain of the England Test team. Stokes has played for England in all three formats. Stokes is regarded as one of England's greatest all-rounders",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/3_14_Captain_Ben_%28cropped%29_%28cropped%29.jpg/330px-3_14_Captain_Ben_%28cropped%29_%28cropped%29.jpg",
    "brand_score": 44.6,
    "tier": "Rising Brand",
    "ig": 3141052,
    "ig_eng": 3.6,
    "yt": 630,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 76.9,
      "eng": 83.3,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "New Balance",
      "Dafabet"
    ],
    "featured": false,
    "tt": 820000,
    "tw": 2100000,
    "fb": 520000,
    "deal_val": 4,
    "age": 34,
    "titles": "ICC WC 2019 · WTC 2021 Hero · Ashes 2015"
  },
  {
    "slug": "nico_hülkenberg",
    "name": "Nico Hülkenberg",
    "short": "HÜLKENBERG",
    "sport": "Formula 1",
    "team": "Haas",
    "nationality": "German",
    "position": "Driver",
    "bio": "Nicolas Hülkenberg is a German racing driver who competes in Formula One for Audi. In endurance racing, Hülkenberg won the 24 Hours of Le Mans in 2015 with Porsche.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/2019_Formula_One_tests_Barcelona%2C_Hulkenberg_%2840287128313%29.jpg/330px-2019_Formula_One_tests_Barcelona%2C_Hulkenberg_%2840287128313%29.jpg",
    "brand_score": 44.2,
    "tier": "Rising Brand",
    "ig": 1050000,
    "ig_eng": 3.9,
    "yt": 2973,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 72.7,
      "eng": 86.8,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Audi",
      "Haas"
    ],
    "featured": false,
    "tt": 520000,
    "tw": 1050000,
    "fb": 320000,
    "deal_val": 3,
    "age": 38,
    "titles": "Le Mans 2015 · 15+ F1 Seasons · Audi Factory"
  },
  {
    "slug": "giannis_antetokounmpo",
    "name": "Giannis Antetokounmpo",
    "short": "ANTETOKOUNMPO",
    "sport": "Basketball",
    "team": "Milwaukee Bucks",
    "nationality": "Greek",
    "position": "Forward",
    "bio": "Giannis Sina Ougko Antetokounmpo is a Nigerian-Greek professional basketball player for the Milwaukee Bucks of the National Basketball Association (NBA). His size, speed, and strength have earned him the nickname \"Greek",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg/330px-Giannis_Antetokounmpo_%2851915153421%29_%28cropped%29.jpg",
    "brand_score": 43.3,
    "tier": "Rising Brand",
    "ig": 15843092,
    "ig_eng": 1.5,
    "yt": 199395,
    "yt_views": 0.2,
    "trend": 21,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 84.4,
      "eng": 58.2,
      "trend": 20.7,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "BBVA",
      "Halo Top"
    ],
    "featured": false,
    "tt": 5300000,
    "tw": 4100000,
    "fb": 4100000,
    "deal_val": 15,
    "age": 31,
    "titles": "NBA Champion 2021 · MVP ×2 · DPOY 2020"
  },
  {
    "slug": "stephen_curry",
    "name": "Stephen Curry",
    "short": "CURRY",
    "sport": "Basketball",
    "team": "Golden State Warriors",
    "nationality": "American",
    "position": "Guard",
    "bio": "Wardell Stephen Curry II, also known as Steph Curry, is an American professional basketball player for the Golden State Warriors of the National Basketball Association (NBA), where he plays as a point guard. Nicknamed",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg/330px-Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg",
    "brand_score": 43.1,
    "tier": "Rising Brand",
    "ig": 57211151,
    "ig_eng": 0.6,
    "yt": 0,
    "yt_views": 0,
    "trend": 46,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 90.6,
      "eng": 11.3,
      "trend": 45.8,
      "spon": 48,
      "val": 0
    },
    "sponsors": [
      "Under Armour",
      "Chase",
      "Rakuten",
      "Nissan",
      "Callaway"
    ],
    "featured": true,
    "tt": 15200000,
    "tw": 17200000,
    "fb": 15000000,
    "deal_val": 50,
    "age": 38,
    "titles": "NBA Champion ×4 · MVP ×2 · Olympic Gold 2024"
  },
  {
    "slug": "carlos_sainz",
    "name": "Carlos Sainz",
    "short": "SAINZ",
    "sport": "Formula 1",
    "team": "Williams",
    "nationality": "Spanish",
    "position": "Driver",
    "bio": "Carlos Sainz Vázquez de Castro is a Spanish racing driver who competes in Formula One for Williams. Sainz has won four Formula One Grands Prix across 12 seasons.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Formula1Gabelhofen2022_%2804%29_%28cropped2%29.jpg/330px-Formula1Gabelhofen2022_%2804%29_%28cropped2%29.jpg",
    "brand_score": 42.9,
    "tier": "Rising Brand",
    "ig": 12563837,
    "ig_eng": 2.6,
    "yt": 434856,
    "yt_views": 0.4,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 83.4,
      "eng": 71.4,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Richard Mille",
      "Estrella Galicia",
      "PokerStars"
    ],
    "featured": false,
    "tt": 4200000,
    "tw": 4100000,
    "fb": 3100000,
    "deal_val": 8,
    "age": 31,
    "titles": "Australian GP 2024 · 3 Race Wins · Williams 2025"
  },
  {
    "slug": "kane_williamson",
    "name": "Kane Williamson",
    "short": "WILLIAMSON",
    "sport": "Cricket",
    "team": "New Zealand",
    "nationality": "New Zealander",
    "position": "Batsman",
    "bio": "Kane Stuart Williamson is a New Zealand international cricketer and a former captain of the New Zealand national team. A right-handed batsman and an occasional off spin bowler, Williamson is the leading run-scorer for",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Kane_Williamson_in_2019.jpg/330px-Kane_Williamson_in_2019.jpg",
    "brand_score": 42.8,
    "tier": "Rising Brand",
    "ig": 1100000,
    "ig_eng": 4.1,
    "yt": 0,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 73.0,
      "eng": 82,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Spartan",
      "Adidas"
    ],
    "featured": false,
    "tt": 480000,
    "tw": 1100000,
    "fb": 520000,
    "deal_val": 3,
    "age": 35,
    "titles": "ICC WTC 2021 · ICC WC Finalist 2019 · NZ Captain"
  },
  {
    "slug": "joe_root",
    "name": "Joe Root",
    "short": "ROOT",
    "sport": "Cricket",
    "team": "England",
    "nationality": "English",
    "position": "Batsman",
    "bio": "Joseph Edward Root is an English international cricketer who plays for England in Tests and ODIs. He captained the Test team from 2017–2022. He plays for Yorkshire in English domestic cricket. Root is currently the",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Joe_Root_HIP1487_%28cropped%29.jpg/330px-Joe_Root_HIP1487_%28cropped%29.jpg",
    "brand_score": 42.5,
    "tier": "Rising Brand",
    "ig": 1200000,
    "ig_eng": 3.4,
    "yt": 795,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 72.8,
      "eng": 80.8,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "New Balance",
      "Gray-Nicolls"
    ],
    "featured": false,
    "tt": 320000,
    "tw": 1050000,
    "fb": 420000,
    "deal_val": 3,
    "age": 35,
    "titles": "England Test Record · 12,500+ Test Runs"
  },
  {
    "slug": "rohit_sharma",
    "name": "Rohit Sharma",
    "short": "SHARMA",
    "sport": "Cricket",
    "team": "India",
    "nationality": "Indian",
    "position": "Batsman",
    "bio": "Rohit Gurunath Sharma is an Indian international cricketer and the former captain of the India national cricket team in all formats of the game. He is a right-handed top-order batter. He represents Mumbai in domestic",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg/500px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg",
    "brand_score": 41,
    "tier": "Rising Brand",
    "ig": 46487885,
    "ig_eng": 3,
    "yt": 0,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 90.0,
      "eng": 59.8,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Adidas",
      "CEAT",
      "Oppo",
      "Lay's"
    ],
    "featured": false,
    "tt": 8100000,
    "tw": 25400000,
    "fb": 15200000,
    "deal_val": 12,
    "age": 39,
    "titles": "T20 WC 2024 · ICC WC 2011 · IPL ×5 Captain"
  },
  {
    "slug": "joel_embiid",
    "name": "Joel Embiid",
    "short": "EMBIID",
    "sport": "Basketball",
    "team": "Philadelphia 76ers",
    "nationality": "Cameroonian",
    "position": "Center",
    "bio": "Joel Hans Embiid is a Cameroonian and American professional basketball player for the Philadelphia 76ers of the National Basketball Association (NBA). After one year of college basketball with the Kansas Jayhawks, he",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Joel_Embiid_2019.jpg/330px-Joel_Embiid_2019.jpg",
    "brand_score": 37.5,
    "tier": "Rising Brand",
    "ig": 7045615,
    "ig_eng": 0.6,
    "yt": 8,
    "yt_views": 0,
    "trend": 15,
    "trend_dir": "rising",
    "market_value": 0,
    "sub": {
      "social": 81.5,
      "eng": 46.6,
      "trend": 14.6,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Nike",
      "Comcast",
      "Stance"
    ],
    "featured": false,
    "tt": 3200000,
    "tw": 4900000,
    "fb": 2100000,
    "deal_val": 10,
    "age": 32,
    "titles": "NBA MVP 2023 · All-Star ×8 · Olympic Gold 2024"
  },
  {
    "slug": "novak_djokovic",
    "name": "Novak Djokovic",
    "short": "DJOKOVIC",
    "sport": "Tennis",
    "team": "nan",
    "nationality": "Serbian",
    "position": "Singles",
    "bio": "Novak Djokovic is a Serbian professional tennis player. Djokovic has been ranked as the world No. 1 in men's singles by the Association of Tennis Professionals (ATP) for a record 428 weeks, finished as the year-end No.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Novak_Djokovic_2024_Paris_Olympics.jpg/330px-Novak_Djokovic_2024_Paris_Olympics.jpg",
    "brand_score": 36.9,
    "tier": "Rising Brand",
    "ig": 16314382,
    "ig_eng": 1,
    "yt": 0,
    "yt_views": 0,
    "trend": 15,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 86.2,
      "eng": 20.2,
      "trend": 15.4,
      "spon": 40,
      "val": 0
    },
    "sponsors": [
      "Lacoste",
      "Head",
      "Seiko",
      "Hublot"
    ],
    "featured": true,
    "tt": 7200000,
    "tw": 10400000,
    "fb": 12400000,
    "deal_val": 30,
    "age": 39,
    "titles": "Grand Slam ×24 · ATP No.1 ×428 Weeks · Olympic Gold 2024"
  },
  {
    "slug": "damian_lillard",
    "name": "Damian Lillard",
    "short": "LILLARD",
    "sport": "Basketball",
    "team": "Milwaukee Bucks",
    "nationality": "American",
    "position": "Guard",
    "bio": "Damian Lamonte Ollie Lillard Sr. is an American professional basketball player for the Portland Trail Blazers of the National Basketball Association (NBA). He also serves as the general manager of the Weber State",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Damian_Lillard_%282021%29_%28cropped%29.jpg/330px-Damian_Lillard_%282021%29_%28cropped%29.jpg",
    "brand_score": 36.6,
    "tier": "Rising Brand",
    "ig": 9620941,
    "ig_eng": 0.3,
    "yt": 67035,
    "yt_views": 0.1,
    "trend": 13,
    "trend_dir": "declining",
    "market_value": 0,
    "sub": {
      "social": 83.2,
      "eng": 43.2,
      "trend": 12.6,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Adidas",
      "Spalding",
      "State Farm"
    ],
    "featured": false,
    "tt": 4400000,
    "tw": 7100000,
    "fb": 3100000,
    "deal_val": 12,
    "age": 35,
    "titles": "NBA Champion 2024 · All-Star ×8"
  },
  {
    "slug": "fernando_alonso",
    "name": "Fernando Alonso",
    "short": "ALONSO",
    "sport": "Formula 1",
    "team": "Aston Martin",
    "nationality": "Spanish",
    "position": "Driver",
    "bio": "Fernando Alonso Díaz is a Spanish racing driver who competes in Formula One for Aston Martin. Alonso has won two Formula One World Drivers' Championship titles, which he won in 2005 and 2006 with Renault, and has won 32",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Alonso-68_%2824710447098%29.jpg/330px-Alonso-68_%2824710447098%29.jpg",
    "brand_score": 35.6,
    "tier": "Rising Brand",
    "ig": 7911543,
    "ig_eng": 0.8,
    "yt": 110999,
    "yt_views": 0.1,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 83.3,
      "eng": 49.4,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Kimoa",
      "Richard Mille",
      "Mapfre",
      "Greenworks"
    ],
    "featured": false,
    "tt": 3100000,
    "tw": 7100000,
    "fb": 8200000,
    "deal_val": 10,
    "age": 44,
    "titles": "F1 World Champion ×2 · 32 Race Wins · Le Mans 24h"
  },
  {
    "slug": "sergio_pérez",
    "name": "Sergio Pérez",
    "short": "PÉREZ",
    "sport": "Formula 1",
    "team": "Red Bull Racing",
    "nationality": "Mexican",
    "position": "Driver",
    "bio": "Sergio Michel \"Checo\" Pérez Mendoza is a Mexican racing driver who competes in Formula One for Cadillac. Pérez was runner-up in the Formula One World Drivers' Championship in 2023 with Red Bull, and has won six Grands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/2021_US_GP_driver_parade_%28cropped2%29.jpg",
    "brand_score": 27.4,
    "tier": "Developing",
    "ig": 8450726,
    "ig_eng": 1.3,
    "yt": 2247,
    "yt_views": 0,
    "trend": 0,
    "trend_dir": "stable",
    "market_value": 0,
    "sub": {
      "social": 83.5,
      "eng": 21.8,
      "trend": 0,
      "spon": 0,
      "val": 0
    },
    "sponsors": [
      "Red Bull",
      "Telcel",
      "Claro"
    ],
    "featured": false,
    "tt": 5100000,
    "tw": 8200000,
    "fb": 5100000,
    "deal_val": 10,
    "age": 36,
    "titles": "Singapore GP 2023 · Monaco GP 2022 · 6 Race Wins"
  }
];
